#!/bin/bash
hadoop_base="/usr/local/hadoop"
hadoop_conf=$hadoop_base/etc/hadoop
cmd=
for arg in $*; do
  cmd="$cmd $arg"
done
for host in $(cat $hadoop_conf/slaves); do
  echo "## $host ##"
  ssh $host "$cmd"
  echo
done
